# Help section
help:
	@echo "Available targets:"
	@echo "  config  - Configure the local testnet"
	@echo "  start   - Start the local testnet"
	@echo "  stop    - Stop the local testnet"
	@echo "  clean   - Clean up the files of the local testnet"

config:
	python3 config.py
start:
	python3 start.py
stop:
	python3 stop.py
clean:
	python3 clean.py
